#!/bin/bash -l
#PBS -l walltime=00:20:00,pmem=2580mb,nodes=1:ppn=3
#PBS -m abe
#PBS -M you@yourUniversity.edu

source activate venv_hominid

mpirun -n 3 \
    hominid \
        ../data/hominid_example_taxon_table_input.txt \
        ../data/hominid_example_snp_input.rvcf \
        ../hominid_example_output.rvcf \
        arcsinsqrt \
        -1 \
        100 \
        no_permutation \
        --maf-lower-cutoff 0.2
